import requests as requests

MaleList = []
FemaleList = []

for i in range(0, 50):
    get_resp = requests.get('https://www.theyfightcrime.org')

    # Request information from theyfightcrime page.

    HTML = str(get_resp.text)

    # Get HTML code from the page what we request.

    Fragment = HTML.split("<P>")

    # The reason why I choose "<P>" as the iterator to split HTML code is because
    # the sentences with he and she are included in a pair of <P></P> tags.

    Sentences = Fragment[1].split("She's")
    # Split the paragraph we get from HTML by "She's" in order to get the first part of the paragraph including "He's"

    Male = Sentences[0]
    # Save the He-Sentence in Male string

    Female = (("She's"+Sentences[1]).split("They"))[0]
    # Use "They" to split another elements in "Sentences" for the She-Sentence

    MaleList.append(str(Male))
    # Save every He-Sentence generated from for-loop to MaleList.

    FemaleList.append(str(Female))
    # Save every She-Sentence generated by for-loop to FemaleList.

with open('/Male.txt', mode='wt', encoding='utf-8') as file:
    file.write('\n'.join(MaleList))
with open('/Female.txt', mode='wt', encoding='utf-8') as file1:
    file1.write('\n'.join(FemaleList))

# Save MaleList to Male.txt and save FemaleList to Female.txt
